tweeter/tweeter/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from tweeter.tweeter.database import Column, Model, SurrogatePK, db, reference_col, relationship
from tweeter.tweeter.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.Binary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

tweeter/tweeter/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from tweeter.tweeter.extensions import csrf_protect

from db_connect import User


@csrf_protect.exempt
class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    @property
    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.select().where(User.login == self.username.data)
        if len(user) > 0:
            self.username.errors.append('Username already registered')
            return False
        return True

tweeter/tweeter/__init__.py
"""Main application package."""

tweeter/tweeter/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template
from tweeter.tweeter import commands, public, user
from tweeter.tweeter.assets import assets
from tweeter.tweeter.extensions import bcrypt, cache, csrf_protect, db, debug_toolbar, login_manager, migrate
from tweeter.tweeter.settings import ProdConfig


def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    app.config.setdefault('WTF_CSRF_ENABLED', False)
    app.config.setdefault('WTF_CSRF_CHECK_DEFAULT', False)
    register_blueprints(app)
    register_errorhandlers(app)
    register_shellcontext(app)
    register_commands(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    # csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        return {
            'db': db,
            'User': user.models.User}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.test)
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)

tweeter/tweeter/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

tweeter/tweeter/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash
from flask_login import login_required
import db_connect

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def members():
    row = db_connect.Account.select()
    accounts = []
    for item in row:
        accounts.append(item.name)
    if request.method == 'POST':
        req = request.form
        flash(req['account'], 'success')
    return render_template('users/members.html', accounts=accounts)

tweeter/tweeter/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

tweeter/tweeter/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Steven Loria</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:sloria1@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

tweeter/tweeter/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Flask
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

tweeter/tweeter/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      Flask

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      <!-- <input type="hidden" name="csrf_token" value="{ csrf_token() }"/> -->
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

tweeter/tweeter/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Добро пожаловать {{ current_user.username }}</h1>
    <h3>Графики</h3>
    <div>
    <h4>Популярные слова</h4>
    <img src="{{ url_for('static', filename='Рейтинг слов.png') }}" />
    </div>

    <div>
    <h4>Периоды</h4>
        <form action="/members" method="post" name="">
            <select name="account">
                {% for item in accounts %}
                    <option>{{ item }}</option>
                {% endfor %}
            </select>
        <p><input type="submit" value="Отправить"></p>
        </form>
    <!-- <img src="{ url_for('static', filename='Выборка периодов.png') }" /> -->
    </div>

    <div>
    <h4>Активность аккаунтов</h4>
    <img src="{{ url_for('static', filename='Активность.png') }}" />
    </div>

{% endblock %}